# Colors (One Dark)

# Default colors
[colors.primary]
# background = '#282c34' # og onedark
# background = '#abb2bf' # edpt-dark
background = '#17181c' # edpt-dark terminal
# background = '#16181B' # edpt-dark terminal blue/green
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
