" When started as "evim", evim.vim will already have done these settings, bail
" out.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  if has('persistent_undo')
    set undofile	" keep an undo file (undo changes after closing)
  endif
endif

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

" For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
	packadd! matchit
endif

packadd! hlyank				" highlight yanked text
packadd! comment			" auto comment with gcc

set background=dark
set number relativenumber   " add line No's & make them relative
set ruler					" show the cursor position all the time
" set showmatch               " show matching makes vim auto indent very slow and unresponsive for a second
set ignorecase              " case insensitive
set hlsearch                " highlight search
set incsearch               " incremental search
set tabstop=4               " number of columns occupied by a tab
" set softtabstop=4           " see multiple spaces as tabstops so <BS> does the right thing
" set expandtab               " converts tabs to white space
" set shiftwidth=4            " width for autoindents
set scrolloff=6				" minimum number of lines above and below cursor
set autoindent              " indent a new line the same amount as the line just typed
set nowrap					" disable wrapping of lines
set mouse=					" diable mouse by removing all option from mouse-=a
set ttymouse=				" diable mouse by removing all option from mouse-=a
" set mouse=a					" enable mouse in all modes
set nocompatible			" use vim settings rather than Vi settings
set wildmode=longest,list   " get bash-like tab completions
set cc=80                 	" set an 80 column border for good coding style
filetype plugin indent on   " allow auto-indenting depending on file type
" set clipboard=unnamedplus   " using system clipboard
" filetype plugin on
" set cursorline              " highlight current cursorline
set ttyfast                 " Speed up scrolling in Vim
" set spell                 " enable spell check (may need to download language package)
" set noswapfile            " disable creating swap file
" set backupdir=~/.cache/vim " Directory to store backup files.
" "stop auto comment a new line
set showcmd 				" display incomplete commands
set termguicolors			" set 24-bit color
set wildmenu				" display completion matches in a status line
syntax on					" turn on synbtax highlighting

autocm FileType * set formatoptions-=cro

" Change cursor shape in different modes
let &t_EI = "\033[2 q"		" NORMAL  █
let &t_SI = "\033[5 q"		" INSERT  |
let &t_SR = "\033[3 q"		" REPLACE _



" # colourscheme #
" https://github.com/joshdick/onedark.vim
if (empty($TMUX))
	if (has("nvim"))
		let $NVIM_TUI_ENABLE_TRUE_COLOR=1
	endif
	if (has("termguicolors"))
		set termguicolors
	endif
endif

syntax on					" syntax highlighting
colorscheme onedark
